let stockProductos = [
    {id: 1, nombre: "T-Shirt Polonia", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga larga", precio: 990, talle: "S", img: './assets/img/rem1.png'},
    {id: 2, nombre: "T-Shirt Polonia", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga larga", precio: 990, talle: "M", img: './assets/img/rem1.png'},
    {id: 3, nombre: "T-Shirt Polonia", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga larga", precio: 990, talle: "L", img: './assets/img/rem1.png'},
    {id: 4, nombre: "T-Shirt Clasica", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga corta", precio: 890, talle: "S", img: './assets/img/remera2.png'},
    {id: 5, nombre: "T-Shirt Clasica", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga corta", precio: 890, talle: "M", img: './assets/img/remera2.png'},
    {id: 6, nombre: "T-Shirt Clasica", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga corta", precio: 890, talle: "L", img: './assets/img/remera2.png'},
    {id: 7, nombre: "T-Shirt LongSleeve", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga larga", precio: 990, talle: "S", img: './assets/img/remera3.png'},
    {id: 8, nombre: "T-Shirt LongSleeve", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga larga", precio: 990, talle: "M", img: './assets/img/remera3.png'},
    {id: 9, nombre: "T-Shirt LongSleeve", tipo: "T-Shirt", cantidad: 1, desc: "Remera casual de manga larga", precio: 990, talle: "L", img: './assets/img/remera3.png'},
    {id: 10, nombre: "Polo Black", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "S", img: './assets/img/polo1.png'},
    {id: 11, nombre: "Polo Black", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "M", img: './assets/img/polo1.png'},
    {id: 12, nombre: "Polo Black", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "L", img: './assets/img/polo1.png'},
    {id: 13, nombre: "Polo SkyBlue", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "S", img: './assets/img/polo2.png'},
    {id: 14, nombre: "Polo SkyBlue", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "M", img: './assets/img/polo2.png'},
    {id: 15, nombre: "Polo SkyBlue", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "L", img: './assets/img/polo2.png'},
    {id: 16, nombre: "Polo Green", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "S", img: './assets/img/polo3.png'},
    {id: 17, nombre: "Polo Green", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "M", img: './assets/img/polo3.png'},
    {id: 18, nombre: "Polo Green", tipo: "Polo", cantidad: 1, desc: "Polo clasica de algodon", precio: 1200, talle: "L", img: './assets/img/polo3.png'},
    {id: 19, nombre: "Pantalones Clasicos", tipo: "Pantalones", cantidad: 1, desc: "Pantalones clasicos de tela", precio: 1500, talle: "S", img: './assets/img/pantalon1.png'},
    {id: 20, nombre: "Pantalones Clasicos", tipo: "Pantalones", cantidad: 1, desc: "Pantalones clasicos de tela", precio: 1500, talle: "M", img: './assets/img/pantalon1.png'},
    {id: 21, nombre: "Pantalones Clasicos", tipo: "Pantalones", cantidad: 1, desc: "Pantalones clasicos de tela", precio: 1500, talle: "L", img: './assets/img/pantalon1.png'},
    {id: 22, nombre: "Pantalon deportivo Gray", tipo: "Pantalones", cantidad: 1, desc: "Pantalones deportivos de algodon", precio: 1600, talle: "S", img: './assets/img/pantalon2.png'},
    {id: 23, nombre: "Pantalon deportivo Gray", tipo: "Pantalones", cantidad: 1, desc: "Pantalones deportivos de algodon", precio: 1600, talle: "M", img: './assets/img/pantalon2.png'},
    {id: 24, nombre: "Pantalon deportivo Gray", tipo: "Pantalones", cantidad: 1, desc: "Pantalones deportivos de algodon", precio: 1600, talle: "L", img: './assets/img/pantalon2.png'},
    {id: 25, nombre: "Pantalon deportivo DarkRed", tipo: "Pantalones", cantidad: 1, desc: "Pantalones deportivos de algodon", precio: 1600, talle: "S", img: './assets/img/pantalon3.png'},
    {id: 26, nombre: "Pantalon deportivo DarkRed", tipo: "Pantalones", cantidad: 1, desc: "Pantalones deportivos de algodon", precio: 1600, talle: "M", img: './assets/img/pantalon3.png'},
    {id: 27, nombre: "Pantalon deportivo DarkRed", tipo: "Pantalones", cantidad: 1, desc: "Pantalones deportivos de algodon", precio: 1600, talle: "L", img: './assets/img/pantalon3.png'},
    {id: 28, nombre: "Chalecos inflados", tipo: "Chalecos", cantidad: 1, desc: "Chalecos inflados de wata", precio: 3600, talle: "S", img: './assets/img/chaleco1.png'},
    {id: 29, nombre: "Chalecos inflados", tipo: "Chalecos", cantidad: 1, desc: "Chalecos inflados de wata", precio: 3600, talle: "M", img: './assets/img/chaleco1.png'},
    {id: 30, nombre: "Chalecos inflados", tipo: "Chalecos", cantidad: 1, desc: "Chalecos inflados de wata", precio: 3600, talle: "L", img: './assets/img/chaleco1.png'},
    {id: 31, nombre: "Chalecos Polar", tipo: "Chalecos", cantidad: 1, desc: "Chalecos de tela polar", precio: 2800, talle: "S", img: './assets/img/chaleco2.png'},
    {id: 32, nombre: "Chalecos Polar", tipo: "Chalecos", cantidad: 1, desc: "Chalecos de tela polar", precio: 2800, talle: "M", img: './assets/img/chaleco2.png'},
    {id: 33, nombre: "Chalecos Polar", tipo: "Chalecos", cantidad: 1, desc: "Chalecos de tela polar", precio: 2800, talle: "L", img: './assets/img/chaleco2.png'},
    {id: 34, nombre: "Canguro gris", tipo: "Canguros", cantidad: 1, desc: "Canguros con bolsillo", precio: 3500, talle: "S", img: './assets/img/canguro1.png'},
    {id: 35, nombre: "Canguro gris", tipo: "Canguros", cantidad: 1, desc: "Canguros con bolsillo", precio: 3500, talle: "M", img: './assets/img/canguro1.png'},
    {id: 36, nombre: "Canguro gris", tipo: "Canguros", cantidad: 1, desc: "Canguros con bolsillo", precio: 3500, talle: "L", img: './assets/img/canguro1.png'},
]